### ISSUE TITLE
/etc/profile.d does not exist on MacOS 10.15

### ISSUE THREAD

**Issue by CaseyLabs** [particledecay/galaxy-asdf#1]
Hi there, thanks for creating this Ansible role. I ran into a small issue with it today:

https://github.com/particledecay/galaxy-asdf/blob/master/tasks/main.yml

Code section:

```
- name: Create bash asdf source script
  template:
    src: "asdf.sh.j2"
    dest: "/etc/profile.d/asdf.sh"
    owner: root
    group: root
    mode: 0755
  become: yes
```

/etc/profile.d appears have been removed on MacOS 10.15 (Catalina), and thus the role fails. I'm not sure if this impacts other MacOS versions.
